version: '3.8'

services:
  # THE DATABASE
  db:
    image: postgres:15-alpine
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # THE MESSAGE BROKER
  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # THE JAVA APPLICATION
  chat-api:
    build: . 
    container_name: chat-spring-api
    restart: on-failure
    ports:
      - "8088:8088"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatdb
      SPRING_DATASOURCE_USERNAME: chatuser
      SPRING_DATASOURCE_PASSWORD: chatpassword
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  pgdata: