# ==========================================
# 1. POSTGRESQL
# ==========================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: chatuser
            - name: POSTGRES_PASSWORD
              value: chatpassword
            - name: POSTGRES_DB
              value: chatdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


# ==========================================
# 2. RABBITMQ
# ==========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # DNS for RabbitMQ
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672


# ==========================================
# 3. JAVA SPRING BOOT API
# ==========================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
        - name: chat-api
          image: pupils-chat-api:latest
          imagePullPolicy: IfNotPresent # Never # prevent to search host in the internet only local
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/chatdb
            - name: SPRING_DATASOURCE_USERNAME
              value: chatuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: chatpassword
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
spec:
  type: NodePort # allow to interact thought a web browser
  selector:
    app: chat-api
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088 # fixed port for entering from the PC
