# default port can be changed here
server.port=8088

# Optional: an application name for the logs
spring.application.name=pupilschat

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest